export type {
  ColorThemeData,
  DotDirCommandsApi,
  DotDirGlobalApi,
  DotDirHostReadyCallback,
  EditorExtensionApi,
  EditorGrammarPayload,
  EditorLanguagePayload,
  EditorProps,
  FsProviderEntry,
  FsProviderExtensionApi,
  FsProviderFactory,
  FsProviderHostApi,
  HostApi,
  ViewerExtensionApi,
  ViewerProps,
} from "@dotdirfm/extension-api";
