import type { CommandContribution } from "./commands";

export const builtInCommandContributions: CommandContribution[] = [
  // ── View ──────────────────────────────────────────────────────────────────
  { command: "toggleHiddenFiles", title: "Toggle Hidden Files", category: "View" },
  { command: "togglePanels", title: "Toggle Panels", category: "View" },
  { command: "runCommands", title: "Run Commands", category: "View", palette: false },
  { command: "showExtensions", title: "Show Extensions", shortTitle: "Plugins", category: "View" },
  { command: "showCommandPalette", title: "Show All Commands", category: "View" },
  { command: "closeViewer", title: "Close Viewer", category: "View" },
  { command: "closeEditor", title: "Close Editor", category: "View" },

  // ── Navigation ────────────────────────────────────────────────────────────
  { command: "switchPanel", title: "Switch Panel", category: "Navigation" },
  { command: "dotdir.focusLeftPanel", title: "Focus Left Panel", category: "Navigation" },
  { command: "dotdir.focusRightPanel", title: "Focus Right Panel", category: "Navigation" },
  { command: "dotdir.openLeftPanelMenu", title: "Open Left Panel Menu", shortTitle: "LeftMn", category: "Navigation", palette: false },
  { command: "dotdir.openRightPanelMenu", title: "Open Right Panel Menu", shortTitle: "RightMn", category: "Navigation", palette: false },
  { command: "dotdir.cancelNavigation", title: "Cancel Navigation", category: "Navigation", palette: false },
  { command: "dotdir.panelEscape", title: "Panel Escape", category: "Navigation", palette: false },
  { command: "cursorUp", title: "Cursor Up", category: "Navigation" },
  { command: "cursorDown", title: "Cursor Down", category: "Navigation" },
  { command: "cursorLeft", title: "Cursor Left", category: "Navigation" },
  { command: "cursorRight", title: "Cursor Right", category: "Navigation" },
  { command: "cursorHome", title: "Cursor to Start", category: "Navigation" },
  { command: "cursorEnd", title: "Cursor to End", category: "Navigation" },
  { command: "cursorPageUp", title: "Cursor Page Up", category: "Navigation" },
  { command: "cursorPageDown", title: "Cursor Page Down", category: "Navigation" },
  { command: "selectUp", title: "Select Up", category: "Navigation" },
  { command: "selectDown", title: "Select Down", category: "Navigation" },
  { command: "selectLeft", title: "Select Left", category: "Navigation" },
  { command: "selectRight", title: "Select Right", category: "Navigation" },
  { command: "selectHome", title: "Select to Start", category: "Navigation" },
  { command: "selectEnd", title: "Select to End", category: "Navigation" },
  { command: "selectPageUp", title: "Select Page Up", category: "Navigation" },
  { command: "selectPageDown", title: "Select Page Down", category: "Navigation" },
  { command: "accept", title: "Accept", category: "Navigation", palette: false },
  { command: "cancel", title: "Cancel", category: "Navigation", palette: false },

  // ── File ──────────────────────────────────────────────────────────────────
  { command: "newTab", title: "New Tab", category: "File" },
  { command: "closeTab", title: "Close Tab", category: "File" },
  { command: "previewInOppositePanel", title: "Open Quick View in Opposite Panel", shortTitle: "View", category: "File", when: "focusPanel && listItemIsFile" },
  { command: "editInOppositePanel", title: "Open Editor in Opposite Panel", shortTitle: "Edit", category: "File", when: "focusPanel && listItemHasEditor" },
  { command: "openCurrentDirInOppositePanelCurrentTab", title: "Open Current Directory in Opposite Panel (Current Tab)", category: "File" },
  { command: "openCurrentDirInOppositePanelNewTab", title: "Open Current Directory in Opposite Panel (New Tab)", category: "File" },
  { command: "openSelectedDirInOppositePanelCurrentTab", title: "Open Selected Directory in Opposite Panel (Current Tab)", category: "File" },
  { command: "openSelectedDirInOppositePanelNewTab", title: "Open Selected Directory in Opposite Panel (New Tab)", category: "File" },
  { command: "openCreateFile", title: "Open / Create File", shortTitle: "New File", category: "File" },
  { command: "viewFile", title: "View File", shortTitle: "View", category: "File", palette: false },
  { command: "editFile", title: "Edit File", shortTitle: "Edit", category: "File", palette: false },

  // ── Application ───────────────────────────────────────────────────────────
  { command: "dotdir.newWindow", title: "New Window", category: "Application", when: "supportsWindowManagement" },
  { command: "dotdir.closeWindow", title: "Close Window", category: "Application", when: "supportsWindowManagement" },
  { command: "dotdir.restartExtensionHost", title: "Restart Extension Host", category: "Application" },
  { command: "dotdir.exit", title: "Exit", shortTitle: "Quit", category: "Application" },

  // ── Terminal ──────────────────────────────────────────────────────────────
  { command: "terminal.execute", title: "Execute in Terminal", category: "Terminal", palette: false },

  // ── File List ─────────────────────────────────────────────────────────────
  { command: "filelist.goToParent", title: "Go to Parent Directory", category: "File List" },
  { command: "filelist.goHome", title: "Go to Home Directory", category: "File List" },
  { command: "filelist.refresh", title: "Refresh", category: "File List" },
  { command: "list.execute", title: "Execute in Terminal", category: "File List", palette: false },
  { command: "list.open", title: "Open", category: "File List" },
  { command: "list.viewFile", title: "View File", shortTitle: "View", category: "File List", when: "focusPanel && listItemHasViewer" },
  { command: "list.editFile", title: "Edit File", shortTitle: "Edit", category: "File List", when: "focusPanel && listItemHasEditor" },
  { command: "list.makeDir", title: "Make Directory", shortTitle: "MkDir", category: "File List" },
  { command: "list.moveToTrash", title: "Move to Trash", shortTitle: "Trash", category: "File List" },
  { command: "list.permanentDelete", title: "Permanently Delete", shortTitle: "Del Perm", category: "File List" },
  { command: "list.copy", title: "Copy", shortTitle: "Copy", category: "File List" },
  { command: "list.move", title: "Move", shortTitle: "Move", category: "File List" },
  { command: "list.rename", title: "Rename", shortTitle: "Rename", category: "File List" },
  { command: "pasteFilename", title: "Paste Filename to Command Line", category: "File List" },
  { command: "pastePath", title: "Paste Path to Command Line", category: "File List" },
  { command: "pasteLeftPanelPath", title: "Paste Left Panel Path to Command Line", category: "File List" },
  { command: "pasteRightPanelPath", title: "Paste Right Panel Path to Command Line", category: "File List" },

  // ── Command Line ──────────────────────────────────────────────────────────
  { command: "commandLine.execute", title: "Execute Command Line", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: "commandLine.clear", title: "Clear Command Line", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: "commandLine.deleteLeft", title: "Delete Left", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: "commandLine.deleteRight", title: "Delete Right", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: "commandLine.moveWordLeft", title: "Move Word Left", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: "commandLine.moveWordRight", title: "Move Word Right", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: "commandLine.left", title: "Move Left", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: "commandLine.right", title: "Move Right", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: "commandLine.home", title: "Move to Start", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: "commandLine.end", title: "Move to End", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: "commandLine.selectAll", title: "Select All", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: "commandLine.selectLeft", title: "Extend Selection Left", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: "commandLine.selectRight", title: "Extend Selection Right", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: "commandLine.selectWordLeft", title: "Extend Selection Word Left", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: "commandLine.selectWordRight", title: "Extend Selection Word Right", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: "commandLine.selectHome", title: "Extend Selection to Start", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: "commandLine.selectEnd", title: "Extend Selection to End", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: "commandLine.copy", title: "Copy Selection", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: "commandLine.cut", title: "Cut Selection", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: "commandLine.paste", title: "Paste from Clipboard", category: "Command Line", when: "focusPanel && commandLineHasText" },
];
