import {
    ACCEPT,
    CANCEL,
    CLEAR,
    CLOSE_EDITOR,
    CLOSE_TAB,
    CLOSE_VIEWER,
    COMMANDLINE_COPY,
    COMMANDLINE_CUT,
    COMMANDLINE_EXECUTE,
    COMMANDLINE_PASTE,
    CURSOR_DOWN,
    CURSOR_END,
    CURSOR_HOME,
    CURSOR_LEFT,
    CURSOR_PAGE_DOWN,
    CURSOR_PAGE_UP,
    CURSOR_RIGHT,
    CURSOR_UP,
    CURSOR_WORD_LEFT,
    CURSOR_WORD_RIGHT,
    DELETE_LEFT,
    DELETE_RIGHT,
    DOTDIR_CANCEL_NAVIGATION,
    DOTDIR_EDITOR_FIND,
    DOTDIR_EDITOR_SAVE,
    DOTDIR_CLOSE_WINDOW,
    DOTDIR_EXIT,
    DOTDIR_FOCUS_LEFT_PANEL,
    DOTDIR_FOCUS_RIGHT_PANEL,
    DOTDIR_NEW_WINDOW,
    DOTDIR_OPEN_LEFT_PANEL_MENU,
    DOTDIR_OPEN_RIGHT_PANEL_MENU,
    DOTDIR_PANEL_ESCAPE,
    DOTDIR_RESTART_EXTENSION_HOST,
    EDIT_FILE,
    EDIT_IN_OPPOSITE_PANEL,
    FILELIST_GO_HOME,
    FILELIST_GO_TO_PARENT,
    FILELIST_REFRESH,
    LIST_COPY,
    LIST_EDIT_FILE,
    LIST_EXECUTE,
    LIST_MAKE_DIR,
    LIST_MOVE,
    LIST_MOVE_TO_TRASH,
    LIST_OPEN,
    LIST_PERMANENT_DELETE,
    LIST_RENAME,
    LIST_VIEW_FILE,
    NEW_TAB,
    OPEN_CREATE_FILE,
    OPEN_CURRENT_DIR_IN_OPPOSITE_PANEL_CURRENT_TAB,
    OPEN_CURRENT_DIR_IN_OPPOSITE_PANEL_NEW_TAB,
    OPEN_SELECTED_DIR_IN_OPPOSITE_PANEL_CURRENT_TAB,
    OPEN_SELECTED_DIR_IN_OPPOSITE_PANEL_NEW_TAB,
    PASTE_FILENAME,
    PASTE_LEFT_PANEL_PATH,
    PASTE_PATH,
    PASTE_RIGHT_PANEL_PATH,
    PREVIEW_IN_OPPOSITE_PANEL,
    RUN_COMMANDS,
    SELECT_ALL,
    SELECT_DOWN,
    SELECT_END,
    SELECT_HOME,
    SELECT_LEFT,
    SELECT_PAGE_DOWN,
    SELECT_PAGE_UP,
    SELECT_RIGHT,
    SELECT_UP,
    SELECT_WORD_LEFT,
    SELECT_WORD_RIGHT,
    SHOW_COMMAND_PALETTE,
    SHOW_FIND_FILES,
    SHOW_EXTENSIONS,
    SWITCH_PANEL,
    SHELL_EXECUTE,
    TOGGLE_HIDDEN_FILES,
    TOGGLE_PANELS,
    VIEW_FILE,
} from "./commandIds";
import type { CommandContribution } from "./commands";

export const builtInCommandContributions: CommandContribution[] = [
  // ── View ──────────────────────────────────────────────────────────────────
  { command: TOGGLE_HIDDEN_FILES, title: "Toggle Hidden Files", category: "View" },
  { command: TOGGLE_PANELS, title: "Toggle Panels", category: "View" },
  { command: RUN_COMMANDS, title: "Run Commands", category: "View", palette: false },
  { command: SHOW_EXTENSIONS, title: "Show Extensions", shortTitle: "Plugins", category: "View" },
  { command: SHOW_FIND_FILES, title: "Find Files", shortTitle: "Find", category: "View", when: "!dialogOpen" },
  { command: SHOW_COMMAND_PALETTE, title: "Show All Commands", category: "View" },
  { command: CLOSE_VIEWER, title: "Close Viewer", category: "View" },
  { command: CLOSE_EDITOR, title: "Close Editor", category: "View" },
  { command: DOTDIR_EDITOR_FIND, title: "Find in Editor", category: "View", when: "focusEditor", palette: false },
  { command: DOTDIR_EDITOR_SAVE, title: "Save File", category: "File", when: "focusEditor", palette: false },

  // ── Navigation ────────────────────────────────────────────────────────────
  { command: SWITCH_PANEL, title: "Switch Panel", category: "Navigation" },
  { command: DOTDIR_FOCUS_LEFT_PANEL, title: "Focus Left Panel", category: "Navigation" },
  { command: DOTDIR_FOCUS_RIGHT_PANEL, title: "Focus Right Panel", category: "Navigation" },
  { command: DOTDIR_OPEN_LEFT_PANEL_MENU, title: "Open Left Panel Menu", shortTitle: "LeftMn", category: "Navigation", palette: false },
  { command: DOTDIR_OPEN_RIGHT_PANEL_MENU, title: "Open Right Panel Menu", shortTitle: "RightMn", category: "Navigation", palette: false },
  { command: DOTDIR_CANCEL_NAVIGATION, title: "Cancel Navigation", category: "Navigation", palette: false },
  { command: DOTDIR_PANEL_ESCAPE, title: "Panel Escape", category: "Navigation", palette: false },
  { command: CURSOR_UP, title: "Cursor Up", category: "Navigation" },
  { command: CURSOR_DOWN, title: "Cursor Down", category: "Navigation" },
  { command: CURSOR_LEFT, title: "Cursor Left", category: "Navigation" },
  { command: CURSOR_RIGHT, title: "Cursor Right", category: "Navigation" },
  { command: CURSOR_HOME, title: "Cursor to Start", category: "Navigation" },
  { command: CURSOR_END, title: "Cursor to End", category: "Navigation" },
  { command: CURSOR_PAGE_UP, title: "Cursor Page Up", category: "Navigation" },
  { command: CURSOR_PAGE_DOWN, title: "Cursor Page Down", category: "Navigation" },
  { command: SELECT_UP, title: "Select Up", category: "Navigation" },
  { command: SELECT_DOWN, title: "Select Down", category: "Navigation" },
  { command: SELECT_LEFT, title: "Select Left", category: "Navigation" },
  { command: SELECT_RIGHT, title: "Select Right", category: "Navigation" },
  { command: SELECT_HOME, title: "Select to Start", category: "Navigation" },
  { command: SELECT_END, title: "Select to End", category: "Navigation" },
  { command: SELECT_PAGE_UP, title: "Select Page Up", category: "Navigation" },
  { command: SELECT_PAGE_DOWN, title: "Select Page Down", category: "Navigation" },
  { command: ACCEPT, title: "Accept", category: "Navigation", palette: false },
  { command: CANCEL, title: "Cancel", category: "Navigation", palette: false },

  // ── File ──────────────────────────────────────────────────────────────────
  { command: NEW_TAB, title: "New Tab", category: "File" },
  { command: CLOSE_TAB, title: "Close Tab", category: "File" },
  { command: PREVIEW_IN_OPPOSITE_PANEL, title: "Open Quick View in Opposite Panel", shortTitle: "View", category: "File", when: "focusPanel && listItemIsFile" },
  { command: EDIT_IN_OPPOSITE_PANEL, title: "Open Editor in Opposite Panel", shortTitle: "Edit", category: "File", when: "focusPanel && listItemHasEditor" },
  { command: OPEN_CURRENT_DIR_IN_OPPOSITE_PANEL_CURRENT_TAB, title: "Open Current Directory in Opposite Panel (Current Tab)", category: "File" },
  { command: OPEN_CURRENT_DIR_IN_OPPOSITE_PANEL_NEW_TAB, title: "Open Current Directory in Opposite Panel (New Tab)", category: "File" },
  { command: OPEN_SELECTED_DIR_IN_OPPOSITE_PANEL_CURRENT_TAB, title: "Open Selected Directory in Opposite Panel (Current Tab)", category: "File" },
  { command: OPEN_SELECTED_DIR_IN_OPPOSITE_PANEL_NEW_TAB, title: "Open Selected Directory in Opposite Panel (New Tab)", category: "File" },
  { command: OPEN_CREATE_FILE, title: "Open / Create File", shortTitle: "New File", category: "File" },
  { command: VIEW_FILE, title: "View File", shortTitle: "View", category: "File", palette: false },
  { command: EDIT_FILE, title: "Edit File", shortTitle: "Edit", category: "File", palette: false },

  // ── Application ───────────────────────────────────────────────────────────
  { command: DOTDIR_NEW_WINDOW, title: "New Window", category: "Application", when: "supportsWindowManagement" },
  { command: DOTDIR_CLOSE_WINDOW, title: "Close Window", category: "Application", when: "supportsWindowManagement" },
  { command: DOTDIR_RESTART_EXTENSION_HOST, title: "Restart Extension Host", category: "Application" },
  { command: DOTDIR_EXIT, title: "Exit", shortTitle: "Quit", category: "Application" },

  // ── Terminal ──────────────────────────────────────────────────────────────
  { command: SHELL_EXECUTE, title: "Execute in Shell", category: "Terminal", palette: false },

  // ── File List ─────────────────────────────────────────────────────────────
  { command: FILELIST_GO_TO_PARENT, title: "Go to Parent Directory", category: "File List" },
  { command: FILELIST_GO_HOME, title: "Go to Home Directory", category: "File List" },
  { command: FILELIST_REFRESH, title: "Refresh", category: "File List" },
  { command: LIST_EXECUTE, title: "Execute in Terminal", category: "File List", palette: false },
  { command: LIST_OPEN, title: "Open", category: "File List" },
  { command: LIST_VIEW_FILE, title: "View File", shortTitle: "View", category: "File List", when: "focusPanel && listItemHasViewer" },
  { command: LIST_EDIT_FILE, title: "Edit File", shortTitle: "Edit", category: "File List", when: "focusPanel && listItemHasEditor" },
  { command: LIST_MAKE_DIR, title: "Make Directory", shortTitle: "MkDir", category: "File List" },
  { command: LIST_MOVE_TO_TRASH, title: "Move to Trash", shortTitle: "Trash", category: "File List" },
  { command: LIST_PERMANENT_DELETE, title: "Permanently Delete", shortTitle: "Del Perm", category: "File List" },
  { command: LIST_COPY, title: "Copy", shortTitle: "Copy", category: "File List" },
  { command: LIST_MOVE, title: "Move", shortTitle: "Move", category: "File List" },
  { command: LIST_RENAME, title: "Rename", shortTitle: "Rename", category: "File List" },
  { command: PASTE_FILENAME, title: "Paste Filename to Command Line", category: "File List" },
  { command: PASTE_PATH, title: "Paste Path to Command Line", category: "File List" },
  { command: PASTE_LEFT_PANEL_PATH, title: "Paste Left Panel Path to Command Line", category: "File List" },
  { command: PASTE_RIGHT_PANEL_PATH, title: "Paste Right Panel Path to Command Line", category: "File List" },

  // ── Command Line ──────────────────────────────────────────────────────────
  { command: COMMANDLINE_EXECUTE, title: "Execute Command Line", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: CLEAR, title: "Clear Command Line", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: DELETE_LEFT, title: "Delete Left", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: DELETE_RIGHT, title: "Delete Right", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: CURSOR_WORD_LEFT, title: "Move Word Left", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: CURSOR_WORD_RIGHT, title: "Move Word Right", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: SELECT_ALL, title: "Select All", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: SELECT_WORD_LEFT, title: "Extend Selection Word Left", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: SELECT_WORD_RIGHT, title: "Extend Selection Word Right", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: COMMANDLINE_COPY, title: "Copy Selection", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: COMMANDLINE_CUT, title: "Cut Selection", category: "Command Line", when: "focusPanel && commandLineHasText" },
  { command: COMMANDLINE_PASTE, title: "Paste from Clipboard", category: "Command Line", when: "focusPanel && commandLineHasText" },
];
